services:
  open-webui-dev:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui-dev
    volumes:
      - open-webui-dev:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.0.163:11434'
      - 'WEBUI_SECRET_KEY='
    networks:
      webui-dev-network:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

volumes:
  open-webui-dev: {}

networks:
  webui-dev-network:
    external: true    # This tells Docker Compose to use the existing network